Fixed library inclusion and unified variable references

diff --git a/bin/uic_attach b/bin/uic_attach
--- a/bin/uic_attach
+++ b/bin/uic_attach
@@ -1,16 +1,16 @@
 #!/bin/bash
 #
-# (c) 2012 YeaSoft Int'l - Leo Moll
+# (c) 2012-2014 YeaSoft Int'l - Leo Moll
 #
-# Version 20120511
-# This script attaches a partition or directory to an Ubuntu
-# installation environment
+# Version 20140508
+# This script attaches a partition or directory to a
+# unified installation environment
 
 #####################################
 # script initialization
 
 # load function library
-source uic_utils
+source /usr/share/yea/uicutils.sh || exit 1
 
 # load user customized configuration data
 [ -f /etc/uic.conf ] &&	source /etc/uic.conf
@@ -28,7 +28,7 @@ MOUNT_PARAMS=
 
 function usage {
 	cat <<EOF
-usage: $SCRIPTNAME [-hv] [-p <mount params>] <device|dir> [<environment name>]
+usage: ${SCRIPTNAME} [-hv] [-p <mount params>] <device|dir> [<environment name>]
 
 Options:
  -p, --mount-params           full set of parameters to pass to the mount
@@ -36,17 +36,15 @@ Options:
  -v, --verbose                increase verbosity
 (-h) --help                   show this help (-h works with no other options)
 
-This script attaches a partition or directory to the specified Ubuntu
+This script attaches a partition or directory to the specified unified
 installation environment so that all subsequent creation and customization
 operations occur in the attached partition or directory.
 
 <environment name> can be omitted if the command is launched from within the
 environment directory. Otherwise it can be:
 
-- an absolute path to the intended environment directory
-  (e.g.: /home/leo/netpoldo-1004-32)
-- a path to the intended environment directory relative to the current
-  directory
+- an absolute path to the intended environment directory (e.g.: /home/kp/alix)
+- a path to the intended environment directory relative to the current dir
 - a path to the intended environment directory relative to /usr/src
 
 EOF
@@ -56,21 +54,21 @@ EOF
 # script section
 
 # Parameter parsing
-PARSER=$(getopt --name "$SCRIPTNAME" --options h,v,p: --longoptions help,verbose,mount-params: -- "$@")
+PARSER=$(getopt --name "${SCRIPTNAME}" --options h,v,p: --longoptions help,verbose,mount-params: -- "$@")
 test_getopt
-eval set -- "$PARSER"
+eval set -- "${PARSER}"
 while true; do
 	case "$1" in
 	-p|--mount-params)		MOUNT_PARAMS="$2"; shift 2;;
 	-h|--help)			show_name; echo; usage; exit 1;;
 	-v|--verbose)			(( VERBOSE++ )); shift;;
 	--)				shift; break;;
-        *)				echo "$SCRIPTNAME: $1: unknown option"; show_error "syntax or usage error (code 1)"; exit 1;;
+        *)				echo "${SCRIPTNAME}: $1: unknown option"; show_error "syntax or usage error (code 1)"; exit 1;;
         esac
 done
 
 # configuration checking
-case "$VERBOSE" in
+case "${VERBOSE}" in
 0)	;;
 1)	show_name;;
 *)	show_name;;
@@ -79,7 +77,7 @@ esac
 # get the mount source
 MOUNT_SOURCE="$1"
 shift
-if [ "$MOUNT_SOURCE" = "" ]; then
+if [ "${MOUNT_SOURCE}" = "" ]; then
 	show_error "Missing mount device or mount directory"
 	exit 3
 fi
@@ -92,13 +90,13 @@ find_environment $1
 verify_environment $1
 
 # check if the environment has already been attached
-if grep "$TARGET/chroot " /proc/mounts > /dev/null; then
+if grep "${TARGET}/chroot " /proc/mounts > /dev/null; then
 	show_error "Installation environment already attached"
 	exit 3
 fi
 
-show_verbose 1 "Attaching $MOUNT_SOURCE to the environment..."
-mkdir -p "$TARGET/chroot"
-mount $MOUNT_PARAMS "$MOUNT_SOURCE" "$TARGET/chroot"
-test_exec mount mount $MOUNT_PARAMS "$MOUNT_SOURCE" "$TARGET/chroot"
+show_verbose 1 "Attaching ${MOUNT_SOURCE} to the environment..."
+mkdir -p "${TARGET}/chroot"
+mount $MOUNT_PARAMS "${MOUNT_SOURCE}" "${TARGET}/chroot"
+test_exec mount mount $MOUNT_PARAMS "${MOUNT_SOURCE}" "${TARGET}/chroot"
 
diff --git a/bin/uic_build b/bin/uic_build
--- a/bin/uic_build
+++ b/bin/uic_build
@@ -1,15 +1,16 @@
 #!/bin/bash
 #
-# (c) 2012 YeaSoft Int'l - Leo Moll
+# (c) 2012-2014 YeaSoft Int'l - Leo Moll
 #
-# Version 20120511
-# This script produces the deliverables of an Ubuntu installation environment
+# Version 20140508
+# This script produces the deliverables of a
+# unified installation environment
 
 #####################################
 # script initialization
 
 # load function library
-source uic_utils
+source /usr/share/yea/uicutils.sh || exit 1
 
 # load user customized configuration data
 [ -f /etc/uic.conf ] &&	source /etc/uic.conf
@@ -29,7 +30,7 @@ VBPARAM=""
 
 function usage {
 	cat <<EOF
-usage: $SCRIPTNAME [-hvlC] [-b <number>[,<number>]..] [<environment name>]
+usage: ${SCRIPTNAME} [-hvlC] [-b <number>[,<number>]..] [<environment name>]
 
 Options:
  -b, --build-target <number>  builds only the build targets with index numbers
@@ -39,7 +40,7 @@ Options:
  -v, --verbose                increase verbosity
 (-h) --help                   show this help (-h works with no other options)
 
-This script produces the deliverables of an Ubuntu installation environment
+This script produces the deliverables of a unified installation environment
 
 <environment name> can be omitted if the command is launched from within the
 environment directory. Otherwise it can be:
@@ -53,16 +54,16 @@ EOF
 
 function list_targets {
 	if [ ${#UIC_TARGET[@]} -eq 0 ]; then
-		echo "There are no build targets defined for $TARGETNAME"
+		echo "There are no build targets defined for ${TARGETNAME}"
 		return 0
 	fi
 
-	echo "The following build targets are defined for $TARGETNAME:"
+	echo "The following build targets are defined for ${TARGETNAME}:"
 	echo
 	echo "Index    Build Target"
 	echo "-------------------------------------------------------"
 	for target_index in $(seq 0 $((${#UIC_TARGET[@]} - 1))); do
-		printf "%-5i    %s\n" $target_index "${UIC_TARGET[$target_index]}"
+		printf "%-5i    %s\n" ${target_index} "${UIC_TARGET[${target_index}]}"
 	done
 	return 0
 }
@@ -72,7 +73,7 @@ function build_target {
 	UIC_BUILDNAME=${1#${UIC_BUILDTYPE}:}
 	shift
 	[ -d "${TARGET}/output" ] || mkdir -p "${TARGET}/output"
-	case "$UIC_BUILDTYPE" in
+	case "${UIC_BUILDTYPE}" in
 	"none")		;;
 	"kernel")	build_target_kernel $@;;
 	"initrd")	build_target_initrd $@;;
@@ -80,11 +81,11 @@ function build_target {
 	"install")	build_target_install $@;;
 	"report")	build_target_report $@;;
 	"archive")	build_target_archive $@;;
-	*)		if [ -x "$TARGET/build/build_target_$UIC_BUILDTYPE" ]; then
-				show_verbose 2 "Calling custom buildscript build_target_$UIC_BUILDTYPE..."
-				source "$TARGET/build/build_target_$UIC_BUILDTYPE"
+	*)		if [ -x "${TARGET}/build/build_target_${UIC_BUILDTYPE}" ]; then
+				show_verbose 2 "Calling custom buildscript build_target_${UIC_BUILDTYPE}..."
+				source "${TARGET}/build/build_target_${UIC_BUILDTYPE}"
 			else
-				show_error "Build type $UIC_BUILDTYPE unknown"
+				show_error "Build type ${UIC_BUILDTYPE} unknown"
 				exit 2
 			fi
 			;;
@@ -99,7 +100,7 @@ function build_target_TEMPLATE {
 	# parse parameters
 	PARSER=$(getopt --name build_target_TEMPLATE --options o: --longoptions output: -- "$@")
 	test_getopt
-	eval set -- "$PARSER"
+	eval set -- "${PARSER}"
 	while true; do
 		case "$1" in
 		-o|--output)	UIC_OUTPUTFILE="${2}"
@@ -130,7 +131,7 @@ function build_target_archive {
 	# parse parameters
 	PARSER=$(getopt --name build_target_archive --options o:,e:,j,z,v --longoptions output:,exclude:,gzip,bzip2,version -- "$@")
 	test_getopt
-	eval set -- "$PARSER"
+	eval set -- "${PARSER}"
 	while [ $# -gt 0 ]; do
 		case "$1" in
 		-o|--output)	UIC_OUTPUTFILE="${2}"
@@ -182,7 +183,7 @@ function build_target_report {
 	# parse parameters
 	PARSER=$(getopt --name build_target_report --options o:,t --longoptions output:,terse -- "$@")
 	test_getopt
-	eval set -- "$PARSER"
+	eval set -- "${PARSER}"
 	while true; do
 		case "$1" in
 		-o|--output)	UIC_OUTPUTFILE="${2}"
@@ -216,7 +217,7 @@ function build_target_install {
 	# parse parameters
 	PARSER=$(getopt --name build_target_install --options o: --longoptions output: -- "$@")
 	test_getopt
-	eval set -- "$PARSER"
+	eval set -- "${PARSER}"
 	while true; do
 		case "$1" in
 		-o|--output)	UIC_OUTPUTPATH="${2}"
@@ -241,7 +242,7 @@ function build_target_install {
 	call_chroot_hook chroot_pre_build_install
 
 	show_verbose 1 "Installing ${TARGETNAME} to ${UIC_OUTPUTPATH}..."
-	cp -a $VBPARAM "${TARGET}/output/." "${UIC_OUTPUTPATH}/"
+	cp -a ${VBPARAM} "${TARGET}/output/." "${UIC_OUTPUTPATH}/"
 
 	call_chroot_hook chroot_post_build_install
 	call_hook post_build_install
@@ -253,7 +254,7 @@ function build_target_kernel {
 	# parse parameters
 	PARSER=$(getopt --name build_target_kernel --options o: --longoptions output: -- "$@")
 	test_getopt
-	eval set -- "$PARSER"
+	eval set -- "${PARSER}"
 	while true; do
 		case "$1" in
 		-o|--output)	UIC_OUTPUTFILE="${2}"
@@ -274,7 +275,7 @@ function build_target_kernel {
 		exit 2
 	fi
 	show_verbose 1 "Creating ${UIC_OUTPUTFILE}..."
-	cp $VBPARAM "${TARGET}/chroot/vmlinuz" "${TARGET}/output/${UIC_OUTPUTFILE}"
+	cp ${VBPARAM} "${TARGET}/chroot/vmlinuz" "${TARGET}/output/${UIC_OUTPUTFILE}"
 
 	call_chroot_hook chroot_post_build_kernel
 	call_hook post_build_kernel
@@ -287,7 +288,7 @@ function build_target_initrd {
 	# parse parameters
 	PARSER=$(getopt --name build_target_initrd --options o:,c: --longoptions output:,config: -- "$@")
 	test_getopt
-	eval set -- "$PARSER"
+	eval set -- "${PARSER}"
 	while true; do
 		case "$1" in
 		-o|--output)	UIC_OUTPUTFILE="${2}"
@@ -311,9 +312,9 @@ function build_target_initrd {
 	cleanup_environment
 
 	show_verbose 1 "Creating ${UIC_OUTPUTFILE}..."
-	[ -f "${UIC_CONFIGFILE}" ] && cp "${UIC_CONFIGFILE}" "${TARGET}/chroot/etc/initramfs-tools/initramfs.conf"
+	[ -f "${UIC_CONFIGFILE}" ] && cp ${VBPARAM} "${UIC_CONFIGFILE}" "${TARGET}/chroot/etc/initramfs-tools/initramfs.conf"
 	chroot "${TARGET}/chroot" /usr/sbin/update-initramfs -u -k all
-	cp  "${TARGET}/chroot/initrd.img" "${TARGET}/output/${UIC_OUTPUTFILE}"
+	cp  ${VBPARAM} "${TARGET}/chroot/initrd.img" "${TARGET}/output/${UIC_OUTPUTFILE}"
 
 	call_chroot_hook chroot_post_build_initrd
 	call_hook post_build_initrd
@@ -326,7 +327,7 @@ function build_target_squashfs {
 	# parse parameters
 	PARSER=$(getopt --name build_target_squashfs --options o:,e: --longoptions output:,exclude: -- "$@")
 	test_getopt
-	eval set -- "$PARSER"
+	eval set -- "${PARSER}"
 	while true; do
 		case "$1" in
 		-o|--output)	UIC_OUTPUTFILE="${2}"
@@ -357,7 +358,7 @@ function build_target_squashfs {
 	show_verbose 1 "Preparing root filesystem..."
 	mkdir -p "${TARGET}/chroot/root/squash/fs"
 	mkdir -p "${TARGET}/chroot/root/squash/out"
-	[ -f ${UIC_EXCLUDEFILE} ] && cp ${UIC_EXCLUDEFILE} "${TARGET}/chroot/root/squash/exclude"
+	[ -f ${UIC_EXCLUDEFILE} ] && cp ${VBPARAM} ${UIC_EXCLUDEFILE} "${TARGET}/chroot/root/squash/exclude"
 	[ -f ${UIC_EXCLUDEFILE} ] || touch "${TARGET}/chroot/root/squash/exclude"
 	echo "root/squash" >> "${TARGET}/chroot/root/squash/exclude"
 	mount -o bind "${TARGET}/chroot" "${TARGET}/chroot/root/squash/fs"
@@ -379,9 +380,9 @@ function build_target_squashfs {
 # script section
 
 # Parameter parsing
-PARSER=$(getopt --name "$SCRIPTNAME" --options h,v,l,C,b: --longoptions help,verbose,list,skip-customization,build-target: -- "$@")
+PARSER=$(getopt --name "${SCRIPTNAME}" --options h,v,l,C,b: --longoptions help,verbose,list,skip-customization,build-target: -- "$@")
 test_getopt
-eval set -- "$PARSER"
+eval set -- "${PARSER}"
 while true; do
 	case "$1" in
 	-h|--help)			show_name; echo; usage; exit 1;;
@@ -390,12 +391,12 @@ while true; do
 	-C|--skip-customization)	SKIP_CUSTOMIZATION=1; shift;;
 	-b|--build-target)		BUILD_TARGETS="$(echo "$2" | tr , " ")"; shift 2;;
 	--)				shift; break;;
-        *)				echo "$SCRIPTNAME: $1: unknown option"; show_error "syntax or usage error (code 1)"; exit 1;;
+        *)				echo "${SCRIPTNAME}: $1: unknown option"; show_error "syntax or usage error (code 1)"; exit 1;;
         esac
 done
 
 # configuration checking
-case "$VERBOSE" in
+case "${VERBOSE}" in
 0)	;;
 1)	show_name;;
 *)	VBPARAM="-v"; show_name;;
@@ -414,7 +415,7 @@ source "$TARGET/uictpl.conf"
 [ -f "$TARGET/custom.conf" ] &&	source "$TARGET/custom.conf"
 test_environment_configuration
 
-if [ $LIST_TARGETS -gt 0 ]; then
+if [ ${LIST_TARGETS} -gt 0 ]; then
 	list_targets
 	exit $?
 fi
@@ -433,24 +434,24 @@ show_verbose 2 "Preparing chroot special filesystems..."
 init_script
 chroot_init
 
-if [ $SKIP_CUSTOMIZATION -eq 0 ]; then
+if [ ${SKIP_CUSTOMIZATION} -eq 0 ]; then
 	apply_customizations
 fi
 
 call_hook pre_build
 call_chroot_hook chroot_pre_build
 
-if [ -n "$BUILD_TARGETS" ]; then
-	for BUILD_TARGET in $BUILD_TARGETS; do
-		if [ $(expr match "$BUILD_TARGET" "[0-9]*") -ne ${#BUILD_TARGET} ]; then
+if [ -n "${BUILD_TARGETS}" ]; then
+	for BUILD_TARGET in ${BUILD_TARGETS}; do
+		if [ $(expr match "${BUILD_TARGET}" "[0-9]*") -ne ${#BUILD_TARGET} ]; then
 			show_error "non numeric build target index specified. use uic build --list to view valid build targets indices"
 			exit 1
 		fi
 	done
-	for BUILD_TARGET in $BUILD_TARGETS; do
-		if [ $BUILD_TARGET -ge 0 -a $BUILD_TARGET -lt ${#UIC_TARGET[@]} ]; then
-			show_verbose 2 "Building specific target $BUILD_TARGET..."
-			build_target ${UIC_TARGET[$BUILD_TARGET]}
+	for BUILD_TARGET in ${BUILD_TARGETS}; do
+		if [ ${BUILD_TARGET} -ge 0 -a ${BUILD_TARGET} -lt ${#UIC_TARGET[@]} ]; then
+			show_verbose 2 "Building specific target ${BUILD_TARGET}..."
+			build_target ${UIC_TARGET[${BUILD_TARGET}]}
 		else
 			show_error "invalid build target index specified. use uic build --list to view valid build targets indices"
 			exit 1
@@ -459,8 +460,8 @@ if [ -n "$BUILD_TARGETS" ]; then
 else
 	show_verbose 2 "Building all targets..."
 	for target_index in $(seq 0 $((${#UIC_TARGET[@]} - 1))); do
-		show_verbose 2 "Building target $target_index..."
-		build_target ${UIC_TARGET[$target_index]}
+		show_verbose 2 "Building target ${target_index}..."
+		build_target ${UIC_TARGET[${target_index}]}
 	done
 fi
 
diff --git a/bin/uic_create b/bin/uic_create
--- a/bin/uic_create
+++ b/bin/uic_create
@@ -1,15 +1,15 @@
 #!/bin/bash
 #
-# (c) 2012 YeaSoft Int'l - Leo Moll
+# (c) 2012-2014 YeaSoft Int'l - Leo Moll
 #
-# Version 20120522
-# This script creates an Ubuntu installation environment
+# Version 20140508
+# This script creates a unified installation environment
 
 #####################################
 # script initialization
 
 # load function library
-source uic_utils
+source /usr/share/yea/uicutils.sh || exit 1
 
 # load user customized configuration data
 [ -f /etc/uic.conf ] &&	source /etc/uic.conf
@@ -26,21 +26,20 @@ QUIET=-qq
 
 function usage {
 	cat <<EOF
-usage: $SCRIPTNAME [-hvF] [<environment name>]
+usage: ${SCRIPTNAME} [-hvF] [<environment name>]
 
 Options:
  -F, --force                  force deletion of existing installation
  -v, --verbose                increase verbosity
 (-h) --help                   show this help (-h works with no other options)
 
-This script creates an Ubuntu installation environment
+This script creates a unified installation environment
 
 <environment name> can be omitted if the command is launched from within the
 environment directory. Otherwise it can be:
 
-- an absolute path to the intended environment directory
-  (e.g.: /home/leo/netpoldo-1004-32)
-- a path to the intended environment directory relative to the current path
+- an absolute path to the intended environment directory (e.g.: /home/kp/alix)
+- a path to the intended environment directory relative to the current dir
 - a path to the intended environment directory relative to /usr/src
 
 EOF
@@ -50,21 +49,21 @@ EOF
 # script section
 
 # Parameter parsing
-PARSER=$(getopt --name "$SCRIPTNAME" --options h,v,F --longoptions help,verbose,force -- "$@")
+PARSER=$(getopt --name "${SCRIPTNAME}" --options h,v,F --longoptions help,verbose,force -- "$@")
 test_getopt
-eval set -- "$PARSER"
+eval set -- "${PARSER}"
 while true; do
 	case "$1" in
 	-h|--help)			show_name; echo; usage; exit 1;;
 	-v|--verbose)			(( VERBOSE++ )); shift;;
 	-F|--force)                     FORCE=1; shift;;
 	--)				shift; break;;
-        *)				echo "$SCRIPTNAME: $1: unknown option"; show_error "syntax or usage error (code 1)"; exit 1;;
+        *)				echo "${SCRIPTNAME}: $1: unknown option"; show_error "syntax or usage error (code 1)"; exit 1;;
         esac
 done
 
 # configuration checking
-case "$VERBOSE" in
+case "${VERBOSE}" in
 0)	;;
 1)	QUIET=-q; show_name;;
 *)	QUIET=""; show_name;;
@@ -77,9 +76,9 @@ test_prereq
 find_environment $1
 verify_environment $1
 
-if [ -d "$TARGET/chroot" ]; then
+if [ -d "${TARGET}/chroot" ]; then
 	# test if there is already a populated installation
-	if [ $(find "$TARGET/chroot" | grep -v "lost+found" | wc -l) -gt 1 -a $FORCE -lt 1 ]; then
+	if [ $(find "${TARGET}/chroot" | grep -v "lost+found" | wc -l) -gt 1 -a ${FORCE} -lt 1 ]; then
 		show_error "Target installation environment ${TARGETNAME} is already existing. Use -F to force cleanup."
 		exit 1
 	fi
@@ -88,24 +87,24 @@ if [ -d "$TARGET/chroot" ]; then
 	test_mountinuse
 
 	# clean up installation area if needed
-	if [ $(find "$TARGET/chroot" | grep -v "lost+found" | wc -l) -gt 1 -a $FORCE -gt 0 ]; then
+	if [ $(find "${TARGET}/chroot" | grep -v "lost+found" | wc -l) -gt 1 -a ${FORCE} -gt 0 ]; then
 		show_verbose 1 "Cleaning up target installation environment ${TARGETNAME}..."
-		if [ -d "$TARGET/chroot/lost+found" ]; then
+		if [ -d "${TARGET}/chroot/lost+found" ]; then
 			show_error "Cannot clean mounted installation environment. Partition should be formatted manually."
 			exit 1
 		else
-			rm -rf "$TARGET/chroot"
-			mkdir -p "$TARGET/chroot"
+			rm -rf "${TARGET}/chroot"
+			mkdir -p "${TARGET}/chroot"
 		fi
 	fi
 else
-	mkdir -p "$TARGET/chroot"
+	mkdir -p "${TARGET}/chroot"
 fi
 
 # load target configuration
 show_verbose 2 "Loading environment configuration..."
-source "$TARGET/uictpl.conf"
-[ -f "$TARGET/custom.conf" ] &&	source "$TARGET/custom.conf"
+source "${TARGET}/uictpl.conf"
+[ -f "${TARGET}/custom.conf" ] && source "${TARGET}/custom.conf"
 test_environment_configuration
 
 # check builder compatibility
@@ -114,11 +113,11 @@ test_builder_compatibility
 show_verbose  1 "Creating target installation environment ${TARGETNAME}..."
 call_hook pre_debootstrap
 if [ -n "${UIC_PREINSTALL}" ]; then
-	debootstrap --include=$(echo ${UIC_PREINSTALL} | tr " " ,) --arch ${UIC_ARCH} ${UIC_RELEASE} "$TARGET/chroot" $(get_filtered_repository)
+	debootstrap --include=$(echo ${UIC_PREINSTALL} | tr " " ,) --arch ${UIC_ARCH} ${UIC_RELEASE} "${TARGET}/chroot" $(get_filtered_repository)
 else
-	debootstrap --arch ${UIC_ARCH} ${UIC_RELEASE} "$TARGET/chroot" $(get_filtered_repository)
+	debootstrap --arch ${UIC_ARCH} ${UIC_RELEASE} "${TARGET}/chroot" $(get_filtered_repository)
 fi
-test_exec debootstrap debootstrap --arch ${UIC_ARCH} ${UIC_RELEASE} "$TARGET/chroot" $(get_filtered_repository)
+test_exec debootstrap debootstrap --arch ${UIC_ARCH} ${UIC_RELEASE} "${TARGET}/chroot" $(get_filtered_repository)
 call_hook post_debootstrap
 
 show_verbose 2 "Preparing chroot special filesystems..."
@@ -133,7 +132,7 @@ call_chroot_hook chroot_pre_installation
 if [ -n "$UIC_PPAS" ]; then
 	for elem in "$UIC_PPAS"; do
 		show_verbose 1 "Adding PPA $elem"
-		add_ppa $elem
+		add_ppa ${elem}
 	done
 fi
 
@@ -143,17 +142,17 @@ exit_apt_proxy
 
 process_locales
 
-if [ -n "$UIC_RECONFIGURE" ]; then
+if [ -n "${UIC_RECONFIGURE}" ]; then
 	show_verbose 1 "Configuring packages..."
-	for RECONF_PACKAGE in $UIC_RECONFIGURE; do
+	for RECONF_PACKAGE in ${UIC_RECONFIGURE}; do
 		RECONF_PKG=$(echo ${RECONF_PACKAGE} | cut -d: -f 1)
 		RECONF_MODE=$(echo ${RECONF_PACKAGE} | cut -d: -f 2)
 		if [ -z "${RECONF_MODE}" ]; then
-			chroot "$TARGET/chroot" dpkg-reconfigure ${RECONF_PKG}
-			test_exec chroot chroot "$TARGET/chroot" dpkg-reconfigure ${RECONF_PKG}
+			chroot "${TARGET}/chroot" dpkg-reconfigure ${RECONF_PKG}
+			test_exec chroot chroot "${TARGET}/chroot" dpkg-reconfigure ${RECONF_PKG}
 		else
-			chroot "$TARGET/chroot" dpkg-reconfigure -f${RECONF_MODE} ${RECONF_PKG}
-			test_exec chroot chroot "$TARGET/chroot" dpkg-reconfigure -f${RECONF_MODE} ${RECONF_PKG}
+			chroot "${TARGET}/chroot" dpkg-reconfigure -f${RECONF_MODE} ${RECONF_PKG}
+			test_exec chroot chroot "${TARGET}/chroot" dpkg-reconfigure -f${RECONF_MODE} ${RECONF_PKG}
 		fi
 	done
 fi
@@ -176,12 +175,12 @@ case "${UIC_ROOTPASSWORD}" in
 "")	show_warning "Password will not be initialized"
 	;;
 "ask")	show_verbose 1 "Asking for root password..."
-	until chroot "$TARGET/chroot" passwd root; do
+	until chroot "${TARGET}/chroot" passwd root; do
 		show_warning "You have to specify a valid password for root"
 	done
 	;;
 *)	show_verbose 1 "Setting root password..."
-	echo -e "${UIC_ROOTPASSWORD}\n${UIC_ROOTPASSWORD}" | chroot "$TARGET/chroot" passwd root  2> /dev/null
+	echo -e "${UIC_ROOTPASSWORD}\n${UIC_ROOTPASSWORD}" | chroot "${TARGET}/chroot" passwd root  2> /dev/null
 	;;
 esac
 
diff --git a/bin/uic_detach b/bin/uic_detach
--- a/bin/uic_detach
+++ b/bin/uic_detach
@@ -1,16 +1,16 @@
 #!/bin/bash
 #
-# (c) 2012 YeaSoft Int'l - Leo Moll
+# (c) 2012-2014 YeaSoft Int'l - Leo Moll
 #
-# Version 20120424
-# This script detaches a partition or directory from an Ubuntu
-# installation environment
+# Version 20140508
+# This script detaches a partition or directory from a
+# unified installation environment
 
 #####################################
 # script initialization
 
 # load function library
-source uic_utils
+source /usr/share/yea/uicutils.sh || exit 1
 
 # load user customized configuration data
 [ -f /etc/uic.conf ] &&	source /etc/uic.conf
@@ -27,7 +27,7 @@ UMOUNT_PARAMS=
 
 function usage {
 	cat <<EOF
-usage: $SCRIPTNAME [-hv] [-p <umount params>] [<environment name>]
+usage: ${SCRIPTNAME} [-hv] [-p <umount params>] [<environment name>]
 
 Options:
  -p, --umount-params          full set of parameters to pass to the umount
@@ -41,10 +41,8 @@ environment (if previously attached).
 <environment name> can be omitted if the command is launched from within the
 environment directory. Otherwise it can be:
 
-- an absolute path to the intended environment directory
-  (e.g.: /home/leo/netpoldo-1004-32)
-- a path to the intended environment directory relative to the current
-  directory
+- an absolute path to the intended environment directory (e.g.: /home/kp/alix)
+- a path to the intended environment directory relative to the current dir
 - a path to the intended environment directory relative to /usr/src
 
 EOF
@@ -54,21 +52,21 @@ EOF
 # script section
 
 # Parameter parsing
-PARSER=$(getopt --name "$SCRIPTNAME" --options h,v,p: --longoptions help,verbose,umount-params: -- "$@")
+PARSER=$(getopt --name "${SCRIPTNAME}" --options h,v,p: --longoptions help,verbose,umount-params: -- "$@")
 test_getopt
-eval set -- "$PARSER"
+eval set -- "${PARSER}"
 while true; do
 	case "$1" in
 	-p|--mount-params)		UMOUNT_PARAMS="$2"; shift 2;;
 	-h|--help)			show_name; echo; usage; exit 1;;
 	-v|--verbose)			(( VERBOSE++ )); shift;;
 	--)				shift; break;;
-        *)				echo "$SCRIPTNAME: $1: unknown option"; show_error "syntax or usage error (code 1)"; exit 1;;
+        *)				echo "${SCRIPTNAME}: $1: unknown option"; show_error "syntax or usage error (code 1)"; exit 1;;
         esac
 done
 
 # configuration checking
-case "$VERBOSE" in
+case "${VERBOSE}" in
 0)	;;
 1)	show_name;;
 *)	show_name;;
@@ -85,10 +83,10 @@ verify_environment $1
 test_mountinuse
 
 # check if the environment has already been attached
-if grep "$TARGET/chroot " /proc/mounts > /dev/null; then
+if grep "${TARGET}/chroot " /proc/mounts > /dev/null; then
 	show_verbose 1 "Detaching the installation environment..."
-	umount $UMOUNT_PARAMS "$TARGET/chroot"
-	test_exec umount umount $UMOUNT_PARAMS "$TARGET/chroot"
+	umount ${UMOUNT_PARAMS} "${TARGET}/chroot"
+	test_exec umount umount ${UMOUNT_PARAMS} "${TARGET}/chroot"
 else
 	show_verbose 0 "No partition attached to the installation environment"
 fi
diff --git a/bin/uic_enter b/bin/uic_enter
--- a/bin/uic_enter
+++ b/bin/uic_enter
@@ -1,15 +1,16 @@
 #!/bin/bash
 #
-# (c) 2012 YeaSoft Int'l - Leo Moll
+# (c) 2012-2014 YeaSoft Int'l - Leo Moll
 #
-# Version 20120331
-# This script enters as chroot into an Ubuntu installation environment
+# Version 20140508
+# This script enters as chroot into a
+# unified installation environment
 
 #####################################
 # script initialization
 
 # load function library
-source uic_utils
+source /usr/share/yea/uicutils.sh || exit 1
 
 # load user customized configuration data
 [ -f /etc/uic.conf ] &&	source /etc/uic.conf
@@ -25,7 +26,7 @@ FORCE=0
 
 function usage {
 	cat <<EOF
-usage: $SCRIPTNAME [-hv] [<environment name>]
+usage: ${SCRIPTNAME} [-hv] [<environment name>]
 
 Options:
  -v, --verbose                increase verbosity
@@ -33,11 +34,11 @@ Options:
 
 This script enters as chroot into an Ubuntu installation environment
 
-<environment name> can be omitted if the command is launched from within the environment
-directory. Otherwise it can be:
+<environment name> can be omitted if the command is launched from within the
+environment directory. Otherwise it can be:
 
-- an absolute path to the intended environment directory (e.g.: /home/leo/netpoldo-1004-32)
-- a path to the intended environment directory relative to the current directory
+- an absolute path to the intended environment directory (e.g.: /home/kp/alix)
+- a path to the intended environment directory relative to the current dir
 - a path to the intended environment directory relative to /usr/src
 
 EOF
@@ -47,20 +48,20 @@ EOF
 # script section
 
 # Parameter parsing
-PARSER=$(getopt --name "$SCRIPTNAME" --options h,v --longoptions help,verbose -- "$@")
+PARSER=$(getopt --name "${SCRIPTNAME}" --options h,v --longoptions help,verbose -- "$@")
 test_getopt
-eval set -- "$PARSER"
+eval set -- "${PARSER}"
 while true; do
 	case "$1" in
 	-h|--help)			show_name; echo; usage; exit 1;;
 	-v|--verbose)			(( VERBOSE++ )); shift;;
 	--)				shift; break;;
-        *)				echo "$SCRIPTNAME: $1: unknown option"; show_error "syntax or usage error (code 1)"; exit 1;;
+        *)				echo "${SCRIPTNAME}: $1: unknown option"; show_error "syntax or usage error (code 1)"; exit 1;;
         esac
 done
 
 # configuration checking
-case "$VERBOSE" in
+case "${VERBOSE}" in
 0)	;;
 1)	show_name;;
 *)	show_name;;
@@ -81,8 +82,8 @@ test_mountinuse
 
 # load target configuration
 show_verbose 2 "Loading environment configuration..."
-source "$TARGET/uictpl.conf"
-[ -f "$TARGET/custom.conf" ] &&	source "$TARGET/custom.conf"
+source "${TARGET}/uictpl.conf"
+[ -f "${TARGET}/custom.conf" ] && source "${TARGET}/custom.conf"
 test_environment_configuration
 
 # check builder compatibility
diff --git a/bin/uic_pack b/bin/uic_pack
--- a/bin/uic_pack
+++ b/bin/uic_pack
@@ -1,15 +1,15 @@
 #!/bin/bash
 #
-# (c) 2012 YeaSoft Int'l - Leo Moll
+# (c) 2012-2014 YeaSoft Int'l - Leo Moll
 #
-# Version 20120331
+# Version 20140508
 # This script packages an installation environment for distribution
 
 #####################################
 # script initialization
 
 # load function library
-source uic_utils
+source /usr/share/yea/uicutils.sh || exit 1
 
 # load user customized configuration data
 [ -f /etc/uic.conf ] &&	source /etc/uic.conf
@@ -26,7 +26,7 @@ ONLYUPDATE=0
 
 function usage {
 	cat <<EOF
-usage: $SCRIPTNAME [-hvu] [-o <output path>] [<environment name>]
+usage: ${SCRIPTNAME} [-hvu] [-o <output path>] [<environment name>]
 
 Options:
  -u, --update                 only update the integrity information
@@ -36,11 +36,11 @@ Options:
 
 This script packages an installation environment for distribution
 
-<environment name> can be omitted if the command is launched from within the environment
-directory. Otherwise it can be:
+<environment name> can be omitted if the command is launched from within the
+environment directory. Otherwise it can be:
 
-- an absolute path to the intended environment directory (e.g.: /home/leo/netpoldo-1004-32)
-- a path to the intended environment directory relative to the current directory
+- an absolute path to the intended environment directory (e.g.: /home/kp/alix)
+- a path to the intended environment directory relative to the current dir
 - a path to the intended environment directory relative to /usr/src
 
 EOF
@@ -50,9 +50,9 @@ EOF
 # script section
 
 # Parameter parsing
-PARSER=$(getopt --name "$SCRIPTNAME" --options h,v,o:,u --longoptions help,verbose,output:,update -- "$@")
+PARSER=$(getopt --name "${SCRIPTNAME}" --options h,v,o:,u --longoptions help,verbose,output:,update -- "$@")
 test_getopt
-eval set -- "$PARSER"
+eval set -- "${PARSER}"
 while true; do
 	case "$1" in
 	-u|--update)			ONLYUPDATE=1; shift;;
@@ -60,12 +60,12 @@ while true; do
 	-v|--verbose)			(( VERBOSE++ )); shift;;
 	-o|--output)			OUTPUTPATH="$2"; shift 2;;
 	--)				shift; break;;
-        *)				echo "$SCRIPTNAME: $1: unknown option"; show_error "syntax or usage error (code 1)"; exit 1;;
+        *)				echo "${SCRIPTNAME}: $1: unknown option"; show_error "syntax or usage error (code 1)"; exit 1;;
         esac
 done
 
 # configuration checking
-case "$VERBOSE" in
+case "${VERBOSE}" in
 0)	;;
 1)	show_name;;
 *)	show_name;;
@@ -84,19 +84,19 @@ fi
 
 # load target configuration
 show_verbose 2 "Loading environment configuration..."
-source "$TARGET/uictpl.conf"
-[ -f "$TARGET/custom.conf" ] &&	source "$TARGET/custom.conf"
+source "${TARGET}/uictpl.conf"
+[ -f "${TARGET}/custom.conf" ] && source "${TARGET}/custom.conf"
 test_environment_configuration
 
 show_verbose 1 "Updating integrity checksums..."
-[ -f "$TARGET/uictpl.md5" ] && rm "$TARGET/uictpl.md5"
+[ -f "${TARGET}/uictpl.md5" ] && rm "${TARGET}/uictpl.md5"
 MD5TEMP=$(mktemp)
-find "$TARGET" -path "$TARGET/output/*" -prune -o -path "$TARGET/chroot/*" -prune -o -path "$TARGET/custom.conf" -prune -o -path "$TARGET/uictpl.md5" -prune -o -type f -print0 | xargs -0 md5sum -b > $MD5TEMP
-SEDFORMULA="s/*"$(echo -n "$TARGET" | sed -e 's/\//\\\//g')"\//*/g" 
-sed -e "$SEDFORMULA" < $MD5TEMP > "$TARGET/uictpl.md5"
-rm "$MD5TEMP"
+find "${TARGET}" -path "${TARGET}/output/*" -prune -o -path "${TARGET}/chroot/*" -prune -o -path "${TARGET}/custom.conf" -prune -o -path "${TARGET}/uictpl.md5" -prune -o -type f -print0 | xargs -0 md5sum -b > ${MD5TEMP}
+SEDFORMULA="s/*"$(echo -n "$TARGET" | sed -e 's/\//\\\//g')"\//*/g"
+sed -e "${SEDFORMULA}" < ${MD5TEMP} > "${TARGET}/uictpl.md5"
+rm "${MD5TEMP}"
 
-if [ $ONLYUPDATE -eq 0 ]; then
+if [ ${ONLYUPDATE} -eq 0 ]; then
 	show_verbose 1 "Packing installation environment..."
 	if [ "${TARGETNAME}" = "${UIC_SRCNAME}" ]; then
 		tar -cjpf "${OUTPUTPATH}/${UIC_SRCNAME}_${UIC_SRCVERSION}.tar.bz2" --directory "${TARGETPATH}" --exclude "${TARGETNAME}/output" --exclude "${TARGETNAME}/chroot" --exclude "${TARGETNAME}/custom.conf" "${TARGETNAME}"
diff --git a/bin/uic_upgrade b/bin/uic_upgrade
--- a/bin/uic_upgrade
+++ b/bin/uic_upgrade
@@ -1,15 +1,15 @@
 #!/bin/bash
 #
-# (c) 2012 YeaSoft Int'l - Leo Moll
+# (c) 2012-2014 YeaSoft Int'l - Leo Moll
 #
-# Version 20120627
-# This script upgrades an Ubuntu installation environment
+# Version 20140508
+# This script upgrades a unified installation environment
 
 #####################################
 # script initialization
 
 # load function library
-source uic_utils
+source /usr/share/yea/uicutils.sh || exit 1
 
 # load user customized configuration data
 [ -f /etc/uic.conf ] &&	source /etc/uic.conf
@@ -27,22 +27,21 @@ QUIET=-qq
 
 function usage {
 	cat <<EOF
-usage: $SCRIPTNAME [-hvIC] [<environment name>]
+usage: ${SCRIPTNAME} [-hvIC] [<environment name>]
 
 Options:
  -I, --do-reinstallations     reinstall all default packages
- -C, --skip-customization     skips the installation customization
+ -C, --skip-customization     skip the installation customization
  -v, --verbose                increase verbosity
 (-h) --help                   show this help (-h works with no other options)
 
-This script upgrades an Ubuntu installation environment
+This script upgrades a unified installation environment
 
 <environment name> can be omitted if the command is launched from within the
 environment directory. Otherwise it can be:
 
-- an absolute path to the intended environment directory
-  (e.g.: /home/leo/netpoldo-1004-32)
-- a path to the intended environment directory relative to the current path
+- an absolute path to the intended environment directory (e.g.: /home/kp/alix)
+- a path to the intended environment directory relative to the current dir
 - a path to the intended environment directory relative to /usr/src
 
 EOF
@@ -52,9 +51,9 @@ EOF
 # script section
 
 # Parameter parsing
-PARSER=$(getopt --name "$SCRIPTNAME" --options h,v,C,I --longoptions help,verbose,skip-customization,do-reinstallations -- "$@")
+PARSER=$(getopt --name "${SCRIPTNAME}" --options h,v,C,I --longoptions help,verbose,skip-customization,do-reinstallations -- "$@")
 test_getopt
-eval set -- "$PARSER"
+eval set -- "${PARSER}"
 while true; do
 	case "$1" in
 	-h|--help)			show_name; echo; usage; exit 1;;
@@ -62,12 +61,12 @@ while true; do
 	-C|--skip-customization)	SKIP_CUSTOMIZATION=1; shift;;
 	-I|--do-reinstallations)	DO_REINSTALLATIONS=1; shift;;
 	--)				shift; break;;
-        *)				echo "$SCRIPTNAME: $1: unknown option"; show_error "syntax or usage error (code 1)"; exit 1;;
+        *)				echo "${SCRIPTNAME}: $1: unknown option"; show_error "syntax or usage error (code 1)"; exit 1;;
         esac
 done
 
 # configuration checking
-case "$VERBOSE" in
+case "${VERBOSE}" in
 0)	;;
 1)	QUIET=-q; show_name;;
 *)	QUIET=""; show_name;;
@@ -88,8 +87,8 @@ test_mountinuse
 
 # load target configuration
 show_verbose 2 "Loading environment configuration..."
-source "$TARGET/uictpl.conf"
-[ -f "$TARGET/custom.conf" ] &&	source "$TARGET/custom.conf"
+source "${TARGET}/uictpl.conf"
+[ -f "${TARGET}/custom.conf" ] && source "${TARGET}/custom.conf"
 test_environment_configuration
 
 # check builder compatibility
@@ -99,9 +98,10 @@ show_verbose 2 "Preparing chroot special filesystems..."
 init_script
 chroot_init
 
-if [ $SKIP_CUSTOMIZATION -eq 0 ]; then
+if [ ${SKIP_CUSTOMIZATION} -eq 0 ]; then
 	apply_customizations
-	# just in case something has changed
+	# just in case something has changed in the locale
+	# configuration provided in the customization
 	process_locales
 fi
 
@@ -116,10 +116,10 @@ update_sources
 update_system
 
 show_verbose 1 "Updating system..."
-chroot $TARGET/chroot apt-get ${QUIET} -y upgrade
-test_exec chroot "$TARGET/chroot" apt-get ${QUIET} -y upgrade
+chroot ${TARGET}/chroot apt-get ${QUIET} -y upgrade
+test_exec chroot "${TARGET}/chroot" apt-get ${QUIET} -y upgrade
 
-if [ $DO_REINSTALLATIONS -gt 0 ]; then
+if [ ${DO_REINSTALLATIONS} -gt 0 ]; then
 	install_software
 	install_packages
 	install_kernel
@@ -127,7 +127,7 @@ fi
 
 exit_apt_proxy
 
-if [ $SKIP_CUSTOMIZATION -eq 0 ]; then
+if [ ${SKIP_CUSTOMIZATION} -eq 0 ]; then
 	# just in case something was changed by apt-get
 	apply_customizations
 fi
