General code style unification

diff --git a/usr/bin/uic_detach b/usr/bin/uic_detach
--- a/usr/bin/uic_detach
+++ b/usr/bin/uic_detach
@@ -2,7 +2,7 @@
 #
 # (c) 2012-2014 YeaSoft Int'l - Leo Moll
 #
-# Version 20140508
+# Version 20140927
 # This script detaches a partition or directory from a
 # unified installation environment
 
@@ -56,12 +56,12 @@ PARSER=$(getopt --name "${SCRIPTNAME}" --options h,v,p: --longoptions help,verbo
 test_getopt
 eval set -- "${PARSER}"
 while true; do
-	case "$1" in
-	-p|--mount-params)		UMOUNT_PARAMS="$2"; shift 2;;
+	case "${1}" in
+	-p|--mount-params)		UMOUNT_PARAMS="${2}"; shift 2;;
 	-h|--help)			show_name; echo; usage; exit 1;;
 	-v|--verbose)			(( VERBOSE++ )); shift;;
 	--)				shift; break;;
-        *)				echo "${SCRIPTNAME}: $1: unknown option"; show_error "syntax or usage error (code 1)"; exit 1;;
+        *)				echo "${SCRIPTNAME}: ${1}: unknown option"; show_error "syntax or usage error (code 1)"; exit 1;;
         esac
 done
 
@@ -76,8 +76,8 @@ esac
 test_prereq
 
 # preflights checks and destination detection
-find_environment $1
-verify_environment $1
+find_environment ${1}
+verify_environment ${1}
 
 # checks if nobody other is working in the environment
 test_mountinuse
diff --git a/usr/bin/uic_pack b/usr/bin/uic_pack
--- a/usr/bin/uic_pack
+++ b/usr/bin/uic_pack
@@ -2,7 +2,7 @@
 #
 # (c) 2012-2014 YeaSoft Int'l - Leo Moll
 #
-# Version 20140508
+# Version 20140927
 # This script packages an installation environment for distribution
 
 #####################################
@@ -54,13 +54,13 @@ PARSER=$(getopt --name "${SCRIPTNAME}" --options h,v,o:,u --longoptions help,ver
 test_getopt
 eval set -- "${PARSER}"
 while true; do
-	case "$1" in
+	case "${1}" in
 	-u|--update)			ONLYUPDATE=1; shift;;
 	-h|--help)			show_name; echo; usage; exit 1;;
 	-v|--verbose)			(( VERBOSE++ )); shift;;
-	-o|--output)			OUTPUTPATH="$2"; shift 2;;
+	-o|--output)			OUTPUTPATH="${2}"; shift 2;;
 	--)				shift; break;;
-        *)				echo "${SCRIPTNAME}: $1: unknown option"; show_error "syntax or usage error (code 1)"; exit 1;;
+        *)				echo "${SCRIPTNAME}: ${1}: unknown option"; show_error "syntax or usage error (code 1)"; exit 1;;
         esac
 done
 
@@ -75,7 +75,7 @@ esac
 test_prereq
 
 # preflights checks and destination detection
-find_environment $1
+find_environment ${1}
 
 if [ ! -d "${OUTPUTPATH}" ]; then
 	show_error "Output path ${OUTPUTPATH} is not existing."
@@ -92,7 +92,7 @@ show_verbose 1 "Updating integrity checksums..."
 [ -f "${TARGET}/uictpl.md5" ] && rm "${TARGET}/uictpl.md5"
 MD5TEMP=$(mktemp)
 find "${TARGET}" -path "${TARGET}/output/*" -prune -o -path "${TARGET}/chroot/*" -prune -o -path "${TARGET}/custom.conf" -prune -o -path "${TARGET}/uictpl.md5" -prune -o -type f -print0 | xargs -0 md5sum -b > ${MD5TEMP}
-SEDFORMULA="s/*"$(echo -n "$TARGET" | sed -e 's/\//\\\//g')"\//*/g"
+SEDFORMULA="s/*"$(echo -n "${TARGET}" | sed -e 's/\//\\\//g')"\//*/g"
 sed -e "${SEDFORMULA}" < ${MD5TEMP} > "${TARGET}/uictpl.md5"
 rm "${MD5TEMP}"
 
