Added support for recipe variants (Closes #12) General code style unification

diff --git a/usr/bin/uic_build b/usr/bin/uic_build
--- a/usr/bin/uic_build
+++ b/usr/bin/uic_build
@@ -2,7 +2,7 @@
 #
 # (c) 2012-2014 YeaSoft Int'l - Leo Moll
 #
-# Version 20140926
+# Version 20140927
 # This script produces the deliverables of a
 # unified installation environment
 
@@ -50,6 +50,19 @@ environment directory. Otherwise it can be:
 - a path to the intended environment directory relative to /usr/src
 
 EOF
+}
+
+function load_build_libraries {
+	if [ -d "${TARGET}/build" ]; then
+		OLDCWD="$(pwd)"; cd "${TARGET}/build"
+		for BUILD_LIB in build_lib_*; do
+			if [ -x ${BUILD_LIB} ]; then
+				show_verbose 2 "Loading custom build library ${BUILD_LIB}"
+				source ${BUILD_LIB}
+			fi
+		done
+		cd "${OLDCWD}"; unset OLDCWD
+	fi
 }
 
 function list_targets {
@@ -349,14 +362,14 @@ PARSER=$(getopt --name "${SCRIPTNAME}" --options h,v,l,C,b: --longoptions help,v
 test_getopt
 eval set -- "${PARSER}"
 while true; do
-	case "$1" in
+	case "${1}" in
 	-h|--help)			show_name; echo; usage; exit 1;;
 	-v|--verbose)			(( VERBOSE++ )); shift;;
 	-l|--list)			LIST_TARGETS=1; shift;;
 	-C|--skip-customization)	SKIP_CUSTOMIZATION=1; shift;;
-	-b|--build-target)		BUILD_TARGETS="$(echo "$2" | tr , " ")"; shift 2;;
+	-b|--build-target)		BUILD_TARGETS="$(echo "${2}" | tr , " ")"; shift 2;;
 	--)				shift; break;;
-        *)				echo "${SCRIPTNAME}: $1: unknown option"; show_error "syntax or usage error (code 1)"; exit 1;;
+        *)				echo "${SCRIPTNAME}: ${1}: unknown option"; show_error "syntax or usage error (code 1)"; exit 1;;
         esac
 done
 
@@ -371,15 +384,13 @@ esac
 test_prereq
 
 # preflights checks and destination detection
-find_environment $1
-verify_environment $1
+find_environment ${1}
+verify_environment ${1}
 
 # load target configuration
-show_verbose 2 "Loading environment configuration..."
-source "$TARGET/uictpl.conf"
-[ -f "$TARGET/custom.conf" ] &&	source "$TARGET/custom.conf"
-test_environment_configuration
+load_environment_configuration
 
+# list targets
 if [ ${LIST_TARGETS} -gt 0 ]; then
 	list_targets
 	exit $?
@@ -394,17 +405,8 @@ test_environment_empty
 # checks if nobody other is working in the environment
 test_mountinuse
 
-# load custom build targets
-if [ -d "${TARGET}/build" ]; then
-	OLDCWD="$(pwd)"; cd "${TARGET}/build"
-	for BUILD_LIB in build_lib_*; do
-		if [ -x ${BUILD_LIB} ]; then
-			show_verbose 2 "Loading custom build library ${BUILD_LIB}"
-			source ${BUILD_LIB}
-		fi
-	done
-	cd "${OLDCWD}"; unset OLDCWD
-fi
+# load custom build libraries
+load_build_libraries
 
 # play the music
 show_verbose 2 "Preparing chroot special filesystems..."
diff --git a/usr/bin/uic_create b/usr/bin/uic_create
--- a/usr/bin/uic_create
+++ b/usr/bin/uic_create
@@ -2,7 +2,7 @@
 #
 # (c) 2012-2014 YeaSoft Int'l - Leo Moll
 #
-# Version 20140514
+# Version 20140927
 # This script creates a unified installation environment
 
 #####################################
@@ -19,18 +19,22 @@ source /usr/share/yea/uicutils.sh || exit 1
 
 # initialize runtime variables
 FORCE=0
+LIST=0
 QUIET=-qq
+UIC_VARIANT=""
 
 #####################################
 # function section
 
 function usage {
 	cat <<EOF
-usage: ${SCRIPTNAME} [-hvF] [<environment name>]
+usage: ${SCRIPTNAME} [-hvlF] [-V <variant>] [<environment name>]
 
 Options:
  -F, --force                  force deletion of existing installation
  -v, --verbose                increase verbosity
+ -l, --list                   show the list of available variants
+ -V, --variant <variant>      create using the specified variant
 (-h) --help                   show this help (-h works with no other options)
 
 This script creates a unified installation environment
@@ -45,20 +49,117 @@ environment directory. Otherwise it can be:
 EOF
 }
 
+function list_variants {
+	if [ $(find . -name 'uictpl.*.conf' | wc -l) -eq 0 ]; then
+		echo "There are no variants available for ${TARGETNAME}"
+		return 0
+	fi
+	echo "The following variants are available for ${TARGETNAME}:"
+	echo
+	echo "Variant              Description"
+	echo "----------------------------------------------------------------------"
+	for variant_name in $(find "${TARGET}" -name 'uictpl.*.conf' | sort); do
+		UIC_VARIANT=$(expr match "${variant_name}" '.*uictpl\.\(.*\)\.conf')
+		UIC_VARDESC=$(expr match "$(grep '^[[:space:]]*UIC_VARDESC' ${variant_name})" '^[[:space:]]*UIC_VARDESC[[:space:]]*=[[:space:]]*"\(.*\)".*$')
+		printf "%-20.20s %s\n" "${UIC_VARIANT}" "${UIC_VARDESC}"
+	done
+	return 0
+}
+
+function test_install_requirements {
+	if [ ! -d "${TARGET}/chroot" ]; then
+		mkdir -p "${TARGET}/chroot"
+		return 0
+	fi
+	# test if there is already a populated installation
+	if [ $(find "${TARGET}/chroot" | grep -v "lost+found" | wc -l) -gt 1 -a ${FORCE} -lt 1 ]; then
+		show_error "Target installation environment ${TARGETNAME} is already existing. Use -F to force cleanup."
+		return 1
+	fi
+	# check if some of the special file system mounts are still existing
+	test_mountinuse
+	# clean up installation area if needed
+	if [ $(find "${TARGET}/chroot" | grep -v "lost+found" | wc -l) -gt 1 -a ${FORCE} -gt 0 ]; then
+		show_verbose 1 "Cleaning up target installation environment ${TARGETNAME}..."
+		if [ -d "${TARGET}/chroot/lost+found" ]; then
+			show_error "Cannot clean mounted installation environment. Partition should be formatted manually."
+			return 1
+		else
+			rm -rf "${TARGET}/chroot"
+			mkdir -p "${TARGET}/chroot"
+		fi
+	fi
+	return 0
+}
+
+function install_do_debootstrap {
+	call_hook pre_debootstrap
+	FILTERED_REPO=$(get_filtered_repository)
+	if [ -n "${UIC_PREINSTALL}" ]; then
+		debootstrap --include=$(echo ${UIC_PREINSTALL} | tr " " ,) --arch ${UIC_ARCH} ${UIC_RELEASE} "${TARGET}/chroot" ${FILTERED_REPO}
+	else
+		debootstrap --arch ${UIC_ARCH} ${UIC_RELEASE} "${TARGET}/chroot" ${FILTERED_REPO}
+	fi
+	test_exec debootstrap debootstrap --arch ${UIC_ARCH} ${UIC_RELEASE} "${TARGET}/chroot" ${FILTERED_REPO}
+	call_hook post_debootstrap
+	unset FILTERED_REPO
+}
+
+function install_do_reconfigure {
+	if [ -z "${UIC_RECONFIGURE}" ]; then
+		return 0
+	fi
+	show_verbose 1 "Configuring packages..."
+	for RECONF_PACKAGE in ${UIC_RECONFIGURE}; do
+		RECONF_PKG=$(echo ${RECONF_PACKAGE} | cut -d: -f 1)
+		RECONF_MODE=$(echo ${RECONF_PACKAGE} | cut -d: -f 2)
+		if [ -z "${RECONF_MODE}" ]; then
+			chroot "${TARGET}/chroot" dpkg-reconfigure ${RECONF_PKG}
+			test_exec chroot chroot "${TARGET}/chroot" dpkg-reconfigure ${RECONF_PKG}
+		else
+			chroot "${TARGET}/chroot" dpkg-reconfigure -f${RECONF_MODE} ${RECONF_PKG}
+			test_exec chroot chroot "${TARGET}/chroot" dpkg-reconfigure -f${RECONF_MODE} ${RECONF_PKG}
+		fi
+	done
+}
+
+function install_do_createusers {
+	case "${UIC_ROOTPASSWORD}" in
+	"")		show_warning "Password will not be initialized"
+			;;
+	"ask")		show_verbose 1 "Asking for root password..."
+			until chroot "${TARGET}/chroot" passwd root; do
+				show_warning "You have to specify a valid password for root"
+			done
+			;;
+	"SHADOW:*")	show_verbose 1 "Setting encrypted root password..."
+			# make sure there is a root password in the file
+			printf "password\npassword\n" | chroot "${TARGET}/chroot" passwd root  2> /dev/null
+			# replace it with the encrypted password
+			sed -i -e "s/root:[^:]*:/root:$(echo -n ${UIC_ROOTPASSWORD:7} | sed -e 's/\//\\\//g'):/" "${TARGET}/chroot/etc/shadow"
+			;;
+	*)		show_verbose 1 "Setting root password..."
+			printf "${UIC_ROOTPASSWORD}\n${UIC_ROOTPASSWORD}\n" | chroot "${TARGET}/chroot" passwd root  2> /dev/null
+			;;
+	esac
+}
+
 #####################################
 # script section
 
 # Parameter parsing
-PARSER=$(getopt --name "${SCRIPTNAME}" --options h,v,F --longoptions help,verbose,force -- "$@")
+PARSER=$(getopt --name "${SCRIPTNAME}" --options h,v,l,F,V: --longoptions help,verbose,list,force,variant: -- "$@")
 test_getopt
 eval set -- "${PARSER}"
 while true; do
-	case "$1" in
+	case "${1}" in
 	-h|--help)			show_name; echo; usage; exit 1;;
 	-v|--verbose)			(( VERBOSE++ )); shift;;
+	-l|--list)			LIST=1; shift;;
 	-F|--force)                     FORCE=1; shift;;
+	-V|--variant)			UIC_VARIANT="${2}"; shift 2;;
 	--)				shift; break;;
-        *)				echo "${SCRIPTNAME}: $1: unknown option"; show_error "syntax or usage error (code 1)"; exit 1;;
+        *)				echo "${SCRIPTNAME}: ${1}: unknown option"; show_error "syntax or usage error (code 1)"; exit 1;;
         esac
 done
 
@@ -73,54 +174,29 @@ esac
 test_prereq
 
 # preflights checks and destination detection
-find_environment $1
-verify_environment $1
+find_environment ${1}
+verify_environment ${1}
 
-if [ -d "${TARGET}/chroot" ]; then
-	# test if there is already a populated installation
-	if [ $(find "${TARGET}/chroot" | grep -v "lost+found" | wc -l) -gt 1 -a ${FORCE} -lt 1 ]; then
-		show_error "Target installation environment ${TARGETNAME} is already existing. Use -F to force cleanup."
-		exit 1
-	fi
+# list variants
+if [ ${LIST} -gt 0 ]; then
+	list_variants
+	exit 0
+fi
 
-	# check if some of the special file system mounts are still existing
-	test_mountinuse
-
-	# clean up installation area if needed
-	if [ $(find "${TARGET}/chroot" | grep -v "lost+found" | wc -l) -gt 1 -a ${FORCE} -gt 0 ]; then
-		show_verbose 1 "Cleaning up target installation environment ${TARGETNAME}..."
-		if [ -d "${TARGET}/chroot/lost+found" ]; then
-			show_error "Cannot clean mounted installation environment. Partition should be formatted manually."
-			exit 1
-		else
-			rm -rf "${TARGET}/chroot"
-			mkdir -p "${TARGET}/chroot"
-		fi
-	fi
-else
-	mkdir -p "${TARGET}/chroot"
+# test creation requirements
+if ! test_install_requirements; then
+	exit 3
 fi
 
 # load target configuration
-show_verbose 2 "Loading environment configuration..."
-source "${TARGET}/uictpl.conf"
-[ -f "${TARGET}/custom.conf" ] && source "${TARGET}/custom.conf"
-test_environment_configuration
+load_environment_configuration "${UIC_VARIANT}"
 
 # check builder compatibility
 test_builder_compatibility
 
-show_verbose  1 "Creating target installation environment ${TARGETNAME}..."
-call_hook pre_debootstrap
-FREPO=$(get_filtered_repository)
-if [ -n "${UIC_PREINSTALL}" ]; then
-	debootstrap --include=$(echo ${UIC_PREINSTALL} | tr " " ,) --arch ${UIC_ARCH} ${UIC_RELEASE} "${TARGET}/chroot" ${FREPO}
-else
-	debootstrap --arch ${UIC_ARCH} ${UIC_RELEASE} "${TARGET}/chroot" ${FREPO}
-fi
-test_exec debootstrap debootstrap --arch ${UIC_ARCH} ${UIC_RELEASE} "${TARGET}/chroot" ${FREPO}
-call_hook post_debootstrap
-
+# finally we can start with the music
+show_verbose  1 "Creating target installation environment ${UIC_SRCNAME}${UIC_VARIANT:+ (${UIC_VARIANT})}..."
+install_do_debootstrap
 show_verbose 2 "Preparing chroot special filesystems..."
 init_script
 chroot_init
@@ -130,12 +206,8 @@ apply_customizations
 call_hook pre_installation
 call_chroot_hook chroot_pre_installation
 
-if [ -n "$UIC_PPAS" ]; then
-	for elem in "$UIC_PPAS"; do
-		show_verbose 1 "Adding PPA $elem"
-		add_ppa ${elem}
-	done
-fi
+install_ppas
+install_uic_tag
 
 init_apt_proxy
 	update_sources
@@ -143,20 +215,7 @@ exit_apt_proxy
 
 process_locales
 
-if [ -n "${UIC_RECONFIGURE}" ]; then
-	show_verbose 1 "Configuring packages..."
-	for RECONF_PACKAGE in ${UIC_RECONFIGURE}; do
-		RECONF_PKG=$(echo ${RECONF_PACKAGE} | cut -d: -f 1)
-		RECONF_MODE=$(echo ${RECONF_PACKAGE} | cut -d: -f 2)
-		if [ -z "${RECONF_MODE}" ]; then
-			chroot "${TARGET}/chroot" dpkg-reconfigure ${RECONF_PKG}
-			test_exec chroot chroot "${TARGET}/chroot" dpkg-reconfigure ${RECONF_PKG}
-		else
-			chroot "${TARGET}/chroot" dpkg-reconfigure -f${RECONF_MODE} ${RECONF_PKG}
-			test_exec chroot chroot "${TARGET}/chroot" dpkg-reconfigure -f${RECONF_MODE} ${RECONF_PKG}
-		fi
-	done
-fi
+install_do_reconfigure
 
 init_apt_proxy
 	# update system
@@ -172,24 +231,7 @@ exit_apt_proxy
 # just in case something was changed by apt-get
 apply_customizations
 
-case "${UIC_ROOTPASSWORD}" in
-"")		show_warning "Password will not be initialized"
-		;;
-"ask")		show_verbose 1 "Asking for root password..."
-		until chroot "${TARGET}/chroot" passwd root; do
-			show_warning "You have to specify a valid password for root"
-		done
-		;;
-"SHADOW:*")	show_verbose 1 "Setting encrypted root password..."
-		# make sure there is a root password in the file
-		printf "password\npassword\n" | chroot "${TARGET}/chroot" passwd root  2> /dev/null
-		# replace it with the encrypted password
-		sed -i -e "s/root:[^:]*:/root:$(echo -n ${UIC_ROOTPASSWORD:7} | sed -e 's/\//\\\//g'):/" "${TARGET}/chroot/etc/shadow"
-		;;
-*)		show_verbose 1 "Setting root password..."
-		printf "${UIC_ROOTPASSWORD}\n${UIC_ROOTPASSWORD}\n" | chroot "${TARGET}/chroot" passwd root  2> /dev/null
-		;;
-esac
+install_do_createusers
 
 call_chroot_hook chroot_post_installation
 call_hook post_installation
diff --git a/usr/bin/uic_enter b/usr/bin/uic_enter
--- a/usr/bin/uic_enter
+++ b/usr/bin/uic_enter
@@ -2,7 +2,7 @@
 #
 # (c) 2012-2014 YeaSoft Int'l - Leo Moll
 #
-# Version 20140508
+# Version 20140927
 # This script enters as chroot into a
 # unified installation environment
 
@@ -52,11 +52,11 @@ PARSER=$(getopt --name "${SCRIPTNAME}" --options h,v --longoptions help,verbose 
 test_getopt
 eval set -- "${PARSER}"
 while true; do
-	case "$1" in
+	case "${1}" in
 	-h|--help)			show_name; echo; usage; exit 1;;
 	-v|--verbose)			(( VERBOSE++ )); shift;;
 	--)				shift; break;;
-        *)				echo "${SCRIPTNAME}: $1: unknown option"; show_error "syntax or usage error (code 1)"; exit 1;;
+        *)				echo "${SCRIPTNAME}: ${1}: unknown option"; show_error "syntax or usage error (code 1)"; exit 1;;
         esac
 done
 
@@ -71,8 +71,8 @@ esac
 test_prereq
 
 # preflights checks and destination detection
-find_environment $1
-verify_environment $1
+find_environment ${1}
+verify_environment ${1}
 
 # checks if the installation environment has been populated
 test_environment_empty
@@ -81,10 +81,7 @@ test_environment_empty
 test_mountinuse
 
 # load target configuration
-show_verbose 2 "Loading environment configuration..."
-source "${TARGET}/uictpl.conf"
-[ -f "${TARGET}/custom.conf" ] && source "${TARGET}/custom.conf"
-test_environment_configuration
+load_environment_configuration
 
 # check builder compatibility
 test_builder_compatibility
diff --git a/usr/bin/uic_purge b/usr/bin/uic_purge
--- a/usr/bin/uic_purge
+++ b/usr/bin/uic_purge
@@ -2,7 +2,7 @@
 #
 # (c) 2012-2014 YeaSoft Int'l - Leo Moll
 #
-# Version 20140508
+# Version 20140927
 # This script purges packages from a
 # unified installation environment
 
@@ -60,7 +60,7 @@ PARSER=$(getopt --name "${SCRIPTNAME}" --options h,v,y,R,C,I --longoptions help,
 test_getopt
 eval set -- "${PARSER}"
 while true; do
-	case "$1" in
+	case "${1}" in
 	-h|--help)			show_name; echo; usage; exit 1;;
 	-v|--verbose)			(( VERBOSE++ )); shift;;
 	-C|--skip-customization)	SKIP_CUSTOMIZATION=1; shift;;
@@ -68,7 +68,7 @@ while true; do
 	-R|--remove)			PURGE=; shift;;
 	-y|--yes)			APTPARAMS="${APTPARAMS} --yes"; shift;;
 	--)				shift; break;;
-        *)				echo "${SCRIPTNAME}: $1: unknown option"; show_error "syntax or usage error (code 1)"; exit 1;;
+        *)				echo "${SCRIPTNAME}: ${1}: unknown option"; show_error "syntax or usage error (code 1)"; exit 1;;
         esac
 done
 
@@ -87,8 +87,8 @@ if [ -f uictpl.conf -a -d files ]; then
 	find_environment
 	verify_environment
 else
-	find_environment $1
-	verify_environment $1
+	find_environment ${1}
+	verify_environment ${1}
 	# eat the environment parameter
 	shift;
 fi
@@ -100,10 +100,7 @@ test_environment_empty
 test_mountinuse
 
 # load target configuration
-show_verbose 2 "Loading environment configuration..."
-source "${TARGET}/uictpl.conf"
-[ -f "${TARGET}/custom.conf" ] && source "${TARGET}/custom.conf"
-test_environment_configuration
+load_environment_configuration
 
 # check builder compatibility
 test_builder_compatibility
@@ -130,6 +127,7 @@ call_chroot_hook chroot_pre_installation
 init_apt_proxy
 
 install_ppas
+install_uic_tag
 
 update_sources
 update_system
